version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    build:
      context: .. # The context points to the parent directory (3_API)
      dockerfile: Dockerfile # Explicitly specify the path to Dockerfile inside the 'docker' folder
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@localhost:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db
